//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRMM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crops_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crops_tbl()
        {
            this.OrderDetalis_tbl = new HashSet<OrderDetalis_tbl>();
            this.StockDetailsRecord_tbl = new HashSet<StockDetailsRecord_tbl>();
        }
    
        public int CropsId { get; set; }
        public string CropsName { get; set; }
        public string Description { get; set; }
        public int CropsCatagoryId { get; set; }
    
        public virtual CropsCatagory_tbl CropsCatagory_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetalis_tbl> OrderDetalis_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDetailsRecord_tbl> StockDetailsRecord_tbl { get; set; }
    }
}
