//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRMM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropsCatagory_tbl
    {
        public int CropsCatagoryId { get; set; }
        public string CropsCatagoryName { get; set; }
        public string Details { get; set; }
        public int CropsId { get; set; }
    
        public virtual Crops_tbl Crops_tbl { get; set; }
    }
}
