//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRMM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRoleTable
    {
        public int EmployeeId { get; set; }
        public string EmployeeRole { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int StorageCompanyId { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsApprove { get; set; }
    
        public virtual StorageCompany_tbl StorageCompany_tbl { get; set; }
        public virtual StockMasterRecordCrops_tbl StockMasterRecordCrops_tbl { get; set; }
        public virtual User_tbl User_tbl { get; set; }
    }
}
