//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRMM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsTemp_tbl
    {
        public int OrderDetailsTempId { get; set; }
        public int ProductId { get; set; }
        public int CropsId { get; set; }
        public int BuyersId { get; set; }
        public int OwnersId { get; set; }
        public decimal Unit { get; set; }
        public decimal TotalPrice { get; set; }
    }
}
