//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRMM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderMaster_tbl()
        {
            this.OrderDetalis_tbl = new HashSet<OrderDetalis_tbl>();
        }
    
        public int OrderId { get; set; }
        public string OrderNo { get; set; }
        public int CropsBuyerId { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime RecordDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetalis_tbl> OrderDetalis_tbl { get; set; }
    }
}
