//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRMM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTempRecord
    {
        public int tmpStockDetailId { get; set; }
        public int CropsCatagoryId { get; set; }
        public decimal StockAmount { get; set; }
        public int EmployeerId { get; set; }
        public string Description { get; set; }
    
        public virtual CropsCatagory_tbl CropsCatagory_tbl { get; set; }
        public virtual EmployeeRoleTable EmployeeRoleTable { get; set; }
    }
}
