//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCRMM_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMasterMainList_tbl
    {
        public int MasterInfoId { get; set; }
        public int StockMasterId { get; set; }
        public int CompanyId { get; set; }
        public decimal StorageAmount { get; set; }
        public decimal ReleaseAmount { get; set; }
        public decimal AvailableStorageAmount { get; set; }
        public bool IsApprove { get; set; }
    
        public virtual StorageCompany_tbl StorageCompany_tbl { get; set; }
        public virtual StockMasterRecordCrops_tbl StockMasterRecordCrops_tbl { get; set; }
    }
}
